"""initial_schema

Revision ID: 79a9fa969c13
Revises: 
Create Date: 2026-04-26 16:13:49.084305

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a9fa969c13'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('consent_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.create_table('donations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('donor_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('stripe_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_table('governance_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_key', sa.String(length=100), nullable=False),
    sa.Column('quorum_q', sa.Integer(), nullable=False),
    sa.Column('theta_reject', sa.Float(), nullable=False),
    sa.Column('theta_accept', sa.Float(), nullable=False),
    sa.Column('w_intelligibility', sa.Float(), nullable=False),
    sa.Column('w_recording', sa.Float(), nullable=False),
    sa.Column('w_compliance', sa.Float(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_params_community_key'), 'governance_params', ['community_key'], unique=False)
    op.create_table('speech_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_name')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contributor_id', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('native_language_code', sa.String(length=20), nullable=False),
    sa.Column('target_language_code', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('speaker_profile', sa.String(length=255), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('hometown', sa.String(length=120), nullable=True),
    sa.Column('residence', sa.String(length=120), nullable=True),
    sa.Column('tribe_ethnicity', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('pair_group_id', sa.String(length=36), nullable=True),
    sa.Column('riddle_part', sa.String(length=20), nullable=True),
    sa.Column('challenge_submission_id', sa.String(length=36), nullable=True),
    sa.Column('reveal_submission_id', sa.String(length=36), nullable=True),
    sa.Column('target_word', sa.String(length=255), nullable=True),
    sa.Column('read_prompt', sa.Text(), nullable=True),
    sa.Column('image_prompt_url', sa.Text(), nullable=True),
    sa.Column('spontaneous_instruction', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('cid', sa.String(length=255), nullable=True),
    sa.Column('contributor_transcription', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_submission_id'], ['submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reveal_submission_id'], ['submissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_category'), 'submissions', ['category'], unique=False)
    op.create_index(op.f('ix_submissions_challenge_submission_id'), 'submissions', ['challenge_submission_id'], unique=False)
    op.create_index(op.f('ix_submissions_contributor_id'), 'submissions', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_submissions_language_code'), 'submissions', ['language_code'], unique=False)
    op.create_index(op.f('ix_submissions_native_language_code'), 'submissions', ['native_language_code'], unique=False)
    op.create_index(op.f('ix_submissions_pair_group_id'), 'submissions', ['pair_group_id'], unique=False)
    op.create_index(op.f('ix_submissions_reveal_submission_id'), 'submissions', ['reveal_submission_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_target_language_code'), 'submissions', ['target_language_code'], unique=False)
    op.create_table('user_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_handle'), 'user_accounts', ['handle'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('community_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('rater_id', sa.String(length=255), nullable=False),
    sa.Column('intelligibility', sa.Integer(), nullable=False),
    sa.Column('recording_quality', sa.Integer(), nullable=False),
    sa.Column('elicitation_compliance', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_ratings_submission_id'), 'community_ratings', ['submission_id'], unique=False)
    op.create_table('contributor_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('source_language_code', sa.String(length=20), nullable=False),
    sa.Column('target_language_code', sa.String(length=20), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('translator_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributor_translations_status'), 'contributor_translations', ['status'], unique=False)
    op.create_index(op.f('ix_contributor_translations_submission_id'), 'contributor_translations', ['submission_id'], unique=False)
    op.create_index(op.f('ix_contributor_translations_translator_id'), 'contributor_translations', ['translator_id'], unique=False)
    op.create_table('dataset_speaker_ids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_code', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_speaker_ids_speaker_code'), 'dataset_speaker_ids', ['speaker_code'], unique=True)
    op.create_index(op.f('ix_dataset_speaker_ids_user_id'), 'dataset_speaker_ids', ['user_id'], unique=True)
    op.create_table('languages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=True),
    sa.Column('is_low_resource', sa.Boolean(), nullable=False),
    sa.Column('speaker_count_approximate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_iso_code'), 'languages', ['iso_code'], unique=True)
    op.create_table('regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_country_id'), 'regions', ['country_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['consent_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('preferred_contribution_type', sa.String(length=50), nullable=False),
    sa.Column('has_speech_impairment', sa.Boolean(), nullable=False),
    sa.Column('impairment_type', sa.String(length=100), nullable=True),
    sa.Column('can_read_sentences', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_speech_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('condition_id', sa.String(length=36), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('is_willing_to_contribute_for_research', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['speech_conditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('dialects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('dialect_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialects_language_id'), 'dialects', ['language_id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_country_id'), 'districts', ['country_id'], unique=False)
    op.create_table('reward_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('pool_name', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_distributed', sa.Float(), nullable=False),
    sa.Column('reward_per_recording', sa.Float(), nullable=False),
    sa.Column('reward_per_validation', sa.Float(), nullable=False),
    sa.Column('reward_per_transcription', sa.Float(), nullable=False),
    sa.Column('reward_per_expert_review', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['reward_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_transactions_user_id'), 'reward_transactions', ['user_id'], unique=False)
    op.create_table('sentence_corpus',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('dialect_id', sa.String(length=36), nullable=True),
    sa.Column('sentence_text', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_corpus_language_id'), 'sentence_corpus', ['language_id'], unique=False)
    op.create_table('user_demographics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age_range', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.String(length=36), nullable=True),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('tribe_ethnicity', sa.String(length=100), nullable=True),
    sa.Column('native_language_id', sa.String(length=36), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['native_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_language_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('dialect_id', sa.String(length=36), nullable=True),
    sa.Column('is_primary_language', sa.Boolean(), nullable=False),
    sa.Column('can_record', sa.Boolean(), nullable=False),
    sa.Column('can_transcribe', sa.Boolean(), nullable=False),
    sa.Column('can_validate', sa.Boolean(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sentence_id', sa.String(length=36), nullable=True),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('dialect_id', sa.String(length=36), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('audio_quality_score', sa.Float(), nullable=True),
    sa.Column('speaker_type', sa.String(length=50), nullable=False),
    sa.Column('recording_device', sa.String(length=50), nullable=False),
    sa.Column('noise_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence_corpus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_language_id'), 'recordings', ['language_id'], unique=False)
    op.create_index(op.f('ix_recordings_status'), 'recordings', ['status'], unique=False)
    op.create_index(op.f('ix_recordings_user_id'), 'recordings', ['user_id'], unique=False)
    op.create_table('source_sentence_pairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_sentence_id', sa.String(length=36), nullable=False),
    sa.Column('target_sentence_id', sa.String(length=36), nullable=False),
    sa.Column('source_language_id', sa.String(length=36), nullable=False),
    sa.Column('target_language_id', sa.String(length=36), nullable=False),
    sa.Column('source_dataset', sa.String(length=100), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['source_sentence_id'], ['sentence_corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_sentence_id'], ['sentence_corpus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_sentence_pairs_source_language_id'), 'source_sentence_pairs', ['source_language_id'], unique=False)
    op.create_index(op.f('ix_source_sentence_pairs_source_sentence_id'), 'source_sentence_pairs', ['source_sentence_id'], unique=False)
    op.create_index(op.f('ix_source_sentence_pairs_target_language_id'), 'source_sentence_pairs', ['target_language_id'], unique=False)
    op.create_index(op.f('ix_source_sentence_pairs_target_sentence_id'), 'source_sentence_pairs', ['target_sentence_id'], unique=False)
    op.create_table('source_translation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_sentence_id', sa.String(length=36), nullable=False),
    sa.Column('source_language_id', sa.String(length=36), nullable=False),
    sa.Column('target_language_id', sa.String(length=36), nullable=False),
    sa.Column('translator_id', sa.String(length=36), nullable=True),
    sa.Column('machine_prefill_text', sa.Text(), nullable=True),
    sa.Column('prefill_provider', sa.String(length=100), nullable=True),
    sa.Column('prefill_confidence', sa.Float(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('reviewed_text', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['source_sentence_id'], ['sentence_corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_translation_tasks_source_language_id'), 'source_translation_tasks', ['source_language_id'], unique=False)
    op.create_index(op.f('ix_source_translation_tasks_source_sentence_id'), 'source_translation_tasks', ['source_sentence_id'], unique=False)
    op.create_index(op.f('ix_source_translation_tasks_status'), 'source_translation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_source_translation_tasks_target_language_id'), 'source_translation_tasks', ['target_language_id'], unique=False)
    op.create_index(op.f('ix_source_translation_tasks_translator_id'), 'source_translation_tasks', ['translator_id'], unique=False)
    op.create_table('dataset_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id', sa.String(length=36), nullable=False),
    sa.Column('final_transcription', sa.Text(), nullable=False),
    sa.Column('speaker_type', sa.String(length=50), nullable=False),
    sa.Column('quality_tier', sa.String(length=50), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['dataset_speaker_ids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_entries_recording_id'), 'dataset_entries', ['recording_id'], unique=True)
    op.create_index(op.f('ix_dataset_entries_speaker_id'), 'dataset_entries', ['speaker_id'], unique=False)
    op.create_table('expert_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('expert_id', sa.String(length=36), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('quality_tier', sa.String(length=50), nullable=False),
    sa.Column('condition_annotation', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('added_to_dictionary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_reviews_recording_id'), 'expert_reviews', ['recording_id'], unique=False)
    op.create_table('pronunciation_dictionary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('dialect_id', sa.String(length=36), nullable=True),
    sa.Column('phoneme_representation', sa.String(length=500), nullable=False),
    sa.Column('audio_reference_id', sa.String(length=36), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_reference_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_dictionary_word'), 'pronunciation_dictionary', ['word'], unique=False)
    op.create_table('source_translation_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_translation_task_id', sa.String(length=36), nullable=False),
    sa.Column('validator_id', sa.String(length=36), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_translation_task_id'], ['source_translation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_translation_task_id', 'validator_id', name='uq_source_translation_validation_task_validator')
    )
    op.create_index(op.f('ix_source_translation_validations_source_translation_task_id'), 'source_translation_validations', ['source_translation_task_id'], unique=False)
    op.create_index(op.f('ix_source_translation_validations_validator_id'), 'source_translation_validations', ['validator_id'], unique=False)
    op.create_table('tips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('contributor_id', sa.String(length=36), nullable=False),
    sa.Column('tipper_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tips_contributor_id'), 'tips', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_tips_recording_id'), 'tips', ['recording_id'], unique=False)
    op.create_index(op.f('ix_tips_tipper_id'), 'tips', ['tipper_id'], unique=False)
    op.create_table('transcription_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('transcriber_id', sa.String(length=36), nullable=False),
    sa.Column('transcribed_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_tasks_recording_id'), 'transcription_tasks', ['recording_id'], unique=False)
    op.create_index(op.f('ix_transcription_tasks_transcriber_id'), 'transcription_tasks', ['transcriber_id'], unique=False)
    op.create_table('validation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('validator_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_clear_audio', sa.Boolean(), nullable=False),
    sa.Column('is_correct_sentence', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_tasks_recording_id'), 'validation_tasks', ['recording_id'], unique=False)
    op.create_index(op.f('ix_validation_tasks_validator_id'), 'validation_tasks', ['validator_id'], unique=False)
    op.create_table('dataset_analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_entry_id', sa.String(length=36), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('research_project_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_entry_id'], ['dataset_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_entry_id')
    )
    op.create_table('transcription_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcription_id', sa.String(length=36), nullable=False),
    sa.Column('validator_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('suggested_correction', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcription_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_validations_transcription_id'), 'transcription_validations', ['transcription_id'], unique=False)
    op.create_table('translation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcription_id', sa.String(length=36), nullable=False),
    sa.Column('translator_id', sa.String(length=36), nullable=False),
    sa.Column('target_language_code', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcription_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_tasks_target_language_code'), 'translation_tasks', ['target_language_code'], unique=False)
    op.create_index(op.f('ix_translation_tasks_transcription_id'), 'translation_tasks', ['transcription_id'], unique=False)
    op.create_index(op.f('ix_translation_tasks_translator_id'), 'translation_tasks', ['translator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_tasks_translator_id'), table_name='translation_tasks')
    op.drop_index(op.f('ix_translation_tasks_transcription_id'), table_name='translation_tasks')
    op.drop_index(op.f('ix_translation_tasks_target_language_code'), table_name='translation_tasks')
    op.drop_table('translation_tasks')
    op.drop_index(op.f('ix_transcription_validations_transcription_id'), table_name='transcription_validations')
    op.drop_table('transcription_validations')
    op.drop_table('dataset_analytics')
    op.drop_index(op.f('ix_validation_tasks_validator_id'), table_name='validation_tasks')
    op.drop_index(op.f('ix_validation_tasks_recording_id'), table_name='validation_tasks')
    op.drop_table('validation_tasks')
    op.drop_index(op.f('ix_transcription_tasks_transcriber_id'), table_name='transcription_tasks')
    op.drop_index(op.f('ix_transcription_tasks_recording_id'), table_name='transcription_tasks')
    op.drop_table('transcription_tasks')
    op.drop_index(op.f('ix_tips_tipper_id'), table_name='tips')
    op.drop_index(op.f('ix_tips_recording_id'), table_name='tips')
    op.drop_index(op.f('ix_tips_contributor_id'), table_name='tips')
    op.drop_table('tips')
    op.drop_index(op.f('ix_source_translation_validations_validator_id'), table_name='source_translation_validations')
    op.drop_index(op.f('ix_source_translation_validations_source_translation_task_id'), table_name='source_translation_validations')
    op.drop_table('source_translation_validations')
    op.drop_index(op.f('ix_pronunciation_dictionary_word'), table_name='pronunciation_dictionary')
    op.drop_table('pronunciation_dictionary')
    op.drop_index(op.f('ix_expert_reviews_recording_id'), table_name='expert_reviews')
    op.drop_table('expert_reviews')
    op.drop_index(op.f('ix_dataset_entries_speaker_id'), table_name='dataset_entries')
    op.drop_index(op.f('ix_dataset_entries_recording_id'), table_name='dataset_entries')
    op.drop_table('dataset_entries')
    op.drop_index(op.f('ix_source_translation_tasks_translator_id'), table_name='source_translation_tasks')
    op.drop_index(op.f('ix_source_translation_tasks_target_language_id'), table_name='source_translation_tasks')
    op.drop_index(op.f('ix_source_translation_tasks_status'), table_name='source_translation_tasks')
    op.drop_index(op.f('ix_source_translation_tasks_source_sentence_id'), table_name='source_translation_tasks')
    op.drop_index(op.f('ix_source_translation_tasks_source_language_id'), table_name='source_translation_tasks')
    op.drop_table('source_translation_tasks')
    op.drop_index(op.f('ix_source_sentence_pairs_target_sentence_id'), table_name='source_sentence_pairs')
    op.drop_index(op.f('ix_source_sentence_pairs_target_language_id'), table_name='source_sentence_pairs')
    op.drop_index(op.f('ix_source_sentence_pairs_source_sentence_id'), table_name='source_sentence_pairs')
    op.drop_index(op.f('ix_source_sentence_pairs_source_language_id'), table_name='source_sentence_pairs')
    op.drop_table('source_sentence_pairs')
    op.drop_index(op.f('ix_recordings_user_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_status'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_language_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_table('user_language_preferences')
    op.drop_table('user_demographics')
    op.drop_index(op.f('ix_sentence_corpus_language_id'), table_name='sentence_corpus')
    op.drop_table('sentence_corpus')
    op.drop_index(op.f('ix_reward_transactions_user_id'), table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_table('reward_pools')
    op.drop_index(op.f('ix_districts_country_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_dialects_language_id'), table_name='dialects')
    op.drop_table('dialects')
    op.drop_table('wallets')
    op.drop_table('user_speech_conditions')
    op.drop_table('user_profiles')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_regions_country_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_languages_iso_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_dataset_speaker_ids_user_id'), table_name='dataset_speaker_ids')
    op.drop_index(op.f('ix_dataset_speaker_ids_speaker_code'), table_name='dataset_speaker_ids')
    op.drop_table('dataset_speaker_ids')
    op.drop_index(op.f('ix_contributor_translations_translator_id'), table_name='contributor_translations')
    op.drop_index(op.f('ix_contributor_translations_submission_id'), table_name='contributor_translations')
    op.drop_index(op.f('ix_contributor_translations_status'), table_name='contributor_translations')
    op.drop_table('contributor_translations')
    op.drop_index(op.f('ix_community_ratings_submission_id'), table_name='community_ratings')
    op.drop_table('community_ratings')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_accounts_handle'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_submissions_target_language_code'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_reveal_submission_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_pair_group_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_native_language_code'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_language_code'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_contributor_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_challenge_submission_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_category'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('speech_conditions')
    op.drop_index(op.f('ix_governance_params_community_key'), table_name='governance_params')
    op.drop_table('governance_params')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('consent_documents')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
